---
- name: "Copying J2 file"
  template:
    src: "templates/policies.json.j2"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
  become: true
  become_method: sudo

- name: "Create .mozzila directory"
  file:
    path: "{{ ansible_env.HOME }}/.mozilla"
    state: directory

- name: "Copy custom settings and bookmarks"
  shell: "cp -r {{ role_path }}/files/firefox {{ ansible_env.HOME }}/.mozilla/"
